### PR TITLE
fix #247: add support for char[]

### LINKED ISSUE #247: ClassCastException when marshalling char[]
The test` org.eclipse.yasson.defaultmapping.collections.CollectionsTest#testMarshallArray` claims support for several arrays, including `char[]`.

Not all supported arrays are tested.

When adding a testcase using a `char[]`, the test fails with a `ClassCastException: [C cannot be cast to [Ljava.lang.Object;`

```
final char[] charArray = new char[] {'a', 'b', 'c'};
assertEquals("[\"a\",\"b\",\"c\"]", jsonb.toJson(charArray));
```

Observed with yasson 1.0.1 and reproduced in MASTER.

### PR DESCRIPTION
**Pull request by frito**
Addded support `char[]`.  Json looks like using `java.lang.Character[]`.

Signed-off-by: Bernd Zeitler <frito.boggie@quantentunnel.de>

### CODE REVIEW

**Comment by frito** [comment]
Addded `char[]` support as mentioned in #247 .

File: src/main/java/org/eclipse/yasson/internal/serializer/CharArraySerializer.java [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+public class CharArraySerializer extends AbstractArraySerializer<char[]> {
+
+    protected CharArraySerializer(SerializerBuilder builder) {
+        super(builder);
+    }
+
+    @Override
+    protected void serializeInternal(char[] obj, JsonGenerator generator, SerializationContext ctx) {
+        for (char c : obj) {
+            generator.write("" + c); // write as string since org.glassfish.json.api.JsonGeneratorImpl does not support writing a char
```
Comment (aguibert) [inline src/main/java/org/eclipse/yasson/internal/serializer/CharArraySerializer.java]: Lets use `Character.valueOf(c).toString()` here, since that will make use of the JDK's built-in CharacterCache

Comment (frito) [reply src/main/java/org/eclipse/yasson/internal/serializer/CharArraySerializer.java]: Ok, I applied the suggested change. Thanks.

File: src/main/java/org/eclipse/yasson/internal/serializer/CharArrayDeserializer.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
+/*******************************************************************************
+ * Copyright (c) 2016 Oracle and/or its affiliates. All rights reserved.
```
Comment (bravehorsie) [inline src/main/java/org/eclipse/yasson/internal/serializer/CharArrayDeserializer.java]: 2019 here

Comment (frito) [reply src/main/java/org/eclipse/yasson/internal/serializer/CharArrayDeserializer.java]: I guess this should be done for the `CharArraySerializer.class`, too.
Does the header needs some more changes but the copyright date?

**Comment by aguibert** [comment]
looks good, thank for the PR @frito! Merging
